"""add platform admin and tenant plan

Revision ID: e9dbdf5b9ae3
Revises: 0002
Create Date: 2026-08-08 16:56:45.465489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default (not just the Python-level default in models.py) is
    # required here, not optional -- NOT NULL with no default fails outright
    # against any tenants/users rows that already exist (which is exactly
    # the state of a dev DB with a real user already signed in). Every
    # existing tenant backfills to "solo" (the actual default plan); every
    # existing user backfills to is_platform_admin=False (the bootstrap
    # PLATFORM_ADMIN_EMAILS check on next login is what promotes the real
    # first admin, not this migration).
    op.add_column('tenants', sa.Column('plan', sa.String(length=32), nullable=False, server_default='solo'))
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    op.drop_column('tenants', 'plan')
    # ### end Alembic commands ###
