"""add store models tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12 09:14:04.560599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'client_id')
    )
    op.create_table('alert_fired_ledger',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('fired', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'client_id')
    )
    op.create_table('data_contexts',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('connector', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'client_id')
    )
    op.create_table('delivery_log_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_log_entries_created_at'), 'delivery_log_entries', ['created_at'], unique=False)
    op.create_index('ix_delivery_log_tenant_report', 'delivery_log_entries', ['tenant_id', 'report_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('report_object', sa.JSON(), nullable=True),
    sa.Column('pdf_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'report_id')
    )
    op.create_index(op.f('ix_generated_reports_client_name'), 'generated_reports', ['client_name'], unique=False)
    op.create_index(op.f('ix_generated_reports_created_at'), 'generated_reports', ['created_at'], unique=False)
    op.create_table('schedules',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('data_source_ref', sa.String(length=255), nullable=False),
    sa.Column('cadence', sa.String(length=16), nullable=False),
    sa.Column('branding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('runs', sa.JSON(), nullable=False),
    sa.Column('client_recipients', sa.JSON(), nullable=False),
    sa.Column('consultant_recipients', sa.JSON(), nullable=False),
    sa.Column('delivery_channel', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_index(op.f('ix_generated_reports_created_at'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_client_name'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index('ix_delivery_log_tenant_report', table_name='delivery_log_entries')
    op.drop_index(op.f('ix_delivery_log_entries_created_at'), table_name='delivery_log_entries')
    op.drop_table('delivery_log_entries')
    op.drop_table('data_contexts')
    op.drop_table('alert_fired_ledger')
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
